# Generated by Django 5.1.2 on 2024-10-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_bookcatalog_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcatalog',
            name='isbn',
            field=models.IntegerField(),
        ),
    ]
