# Generated by Django 5.1.2 on 2024-11-06 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_bookcatalog_isbn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookCatalog',
        ),
    ]
